### ISSUE TITLE
Envrc on linux

### ISSUE THREAD

**Issue by tbagrel1** [smelc/tn-fp-haskell-course#4]
There is a `.envrc` file at the root of the directory (for Windows user I suppose?), that conflicts with the need of an `.envrc` file containing `use nix` to use `direnv` on linux/macos.

Is there something we can do about that?

**Comment by smelc** [comment]
The existing top-level `.envrc` file is the one I use personally to provision ghc and hls, without using nix; on Ubuntu 22.04. If you want to change it so that ghc and hls are provisioned using nix, and which is `nix-shell` compatible, please go ahead. If the whole nix setup is also shared with the CI, that's even better :wink:

**Comment by tbagrel1** [comment]
> If you want to change it so that ghc and hls are provisioned using nix, and which is nix-shell compatible, please go ahead. If the whole nix setup is also shared with the CI, that's even better

That's already the case (and what I use locally ATM)

It should be closed by #5
